
spring:
    application:
      name: UserService
      cloud:
          gateway:
              enabled: false



eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true
server:
    port: 8082
